

---
- name: add ppa key
  apt_key:
    id: 7BB9C367
    keyserver: keyserver.ubuntu.com
    state: present
    
- name: Add ansible repository.
  apt_repository: 
    repo: 'ppa:ansible/ansible'

- name: Update apt cache.
  apt: 
    update_cache: true 
    cache_valid_time: 86400

- name: Install Ansible.
  apt:
    name: ansible="{{ ansible_pip_version }}"
    state: "present"
